### PR TITLE
Java11 build

### PR DESCRIPTION
**Pull request by anthodamato**
Hi Jody.
I made the following changes:
- fixed the Java 8 unit test
- building with Java 11
- javadoc improvements

Antonio

### CODE REVIEW

**Comment by jgrassel** [comment]
Hey, Antonio!  Thank you for your contribution!

**Comment by anthodamato** [comment]
Hi Jody, you're welcome.
I changed the version number as well.
I made some improvements to Serp in order to build OpenJPA with Java 11. With these changes and other changes on OpenJPA the unit tests pass.

Antonio

**Comment by jgrassel** [comment]
Hello, Antonio.  Question, are both PRs intended to be merged, or does one supercede the other?

**Comment by anthodamato** [comment]
Hi Jody.
Please, ignore the 'Java11 build' PR for now.
'Java8' PR can be merged if you agree.
I did the following changes:

- Java 8 build
- javadoc improvements
- updated junit to version 5 
- fixed the Java 8 unit test
- 'serp.util.Numbers' class refactoring
- added 'package' and 'module' constant pool entries

**Pull request closed without merging**
